<?php

/**
 * This file is part of the Phalcon API.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phalcon\Api\Domain\Services\Http;

/**
 * Enumeration for Http Codes. These are not only the regular HTTP codes
 * but also the ones generated by the application
 */
enum HttpCodesEnum: int
{
    /**
     * Regular HTTP codes
     */
    case OK           = 200;
    case BadRequest   = 400;
    case NotFound     = 404;
    case Unauthorized = 401;

    /**
     * Application specific codes
     */
    case AppMalformedPayload = 3400;
    case AppRecordsNotFound  = 3401;
    case AppResourceNotFound = 3402;
    case AppUnauthorized     = 3403;
    case AppInvalidArguments = 3409;

    /**
     * Returns an array with the value as key and text as value
     *
     * @return array<integer, string>
     */
    public function error(): array
    {
        return [$this->value => $this->text()];
    }

    /**
     * Return the text associated with the option
     *
     * @return string
     */
    public function text(): string
    {
        return match ($this) {
            self::OK                  => 'OK',
            self::BadRequest          => 'Bad Request',
            self::NotFound            => 'Not Found',
            self::AppMalformedPayload => 'Malformed payload',
            self::AppRecordsNotFound  => 'Record(s) not found',
            self::AppResourceNotFound => 'Resource not found',
            self::Unauthorized,
            self::AppUnauthorized     => 'Unauthorized',
            self::AppInvalidArguments => 'Invalid arguments provided',
        };
    }
}
